spring:
  datasource:
    url:  jdbc:mysql://192.168.99.100/demo_db
    username: root
    password: rootpassword
    hikari:
      driverClassName: com.mysql.cj.jdbc.Driver
security:
    basic:
        enabled: false